config/routes.rb
Rails.application.routes.draw do
  resources :facilities
  resources :users
  resources :parks

  root 'home#index'

  post '/search' => 'search_api#search'

end

app/models/facility.rb
class Facility < ActiveRecord::Base

	belongs_to :park

end

app/models/park.rb
class Park < ActiveRecord::Base

	acts_as_mappable
	before_validation :geocode_address, :only => [:create, :update]

	has_many :users
	has_many :facilities

	private

  def geocode_address
    return if address.blank?
    geo=Geokit::Geocoders::MultiGeocoder.geocode ("#{self.address}, Toronto, Canada")
    errors.add(:address, "Could not Geocode address") if !geo.success
    self.lat, self.lng = geo.lat, geo.lng if geo.success
  end

	def facility_name
		csv = ""
		facilities.each do |facility|
	  	csv += facility.name
		end
		csv
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :parks
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  # GET /facilities
  # GET /facilities.json
  def index
    @facilities = Facility.all
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
  end

  # GET /facilities/new
  def new
    @facility = Facility.new
  end

  # GET /facilities/1/edit
  def edit
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, notice: 'Facility was successfully created.' }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facilities/1
  # PATCH/PUT /facilities/1.json
  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to @facility, notice: 'Facility was successfully updated.' }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility.destroy
    respond_to do |format|
      format.html { redirect_to facilities_url, notice: 'Facility was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:name, :displayname)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@parks = Park.all
	end
	
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :set_park, only: [:show, :edit, :update, :destroy]

  # GET /parks
  # GET /parks.json
  def index
    @parks = Park.all
    # binding.pry
    if params[:search]
      @parks = Park.search(params[:search]).order("created_at DESC")
    # else
    #   @parks = Park.all.order('created_at DESC')
    end

    # if params[:search_displayname] != ""
    #   @parks = @parks.search(params[:search_displayname])
    # end 

  end

  # GET /parks/1
  # GET /parks/1.json
  def show
  end

  # GET /parks/new
  def new
    @park = Park.new
  end

  # GET /parks/1/edit
  def edit
  end

  # POST /parks
  # POST /parks.json
  def create
    @park = Park.new(park_params)

    respond_to do |format|
      if @park.save
        format.html { redirect_to @park, notice: 'Park was successfully created.' }
        format.json { render :show, status: :created, location: @park }
      else
        format.html { render :new }
        format.json { render json: @park.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parks/1
  # PATCH/PUT /parks/1.json
  def update
    respond_to do |format|
      if @park.update(park_params)
        format.html { redirect_to @park, notice: 'Park was successfully updated.' }
        format.json { render :show, status: :ok, location: @park }
      else
        format.html { render :edit }
        format.json { render json: @park.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parks/1
  # DELETE /parks/1.json
  def destroy
    @park.destroy
    respond_to do |format|
      format.html { redirect_to parks_url, notice: 'Park was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_park
      @park = Park.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def park_params
      params.require(:park).permit(:name, :address, :postalcode, :imgageurl, :cleanliness, :welllit)
    end

end

app/controllers/search_api_controller.rb
class SearchApiController < ApplicationController

	def search
		@parks = Park.all
		if params[:track] != "" 
      case params[:track]
        when "Track" 
          @parks = @parks.joins(:facilities).where("facilities.displayname like ?", "%Track%")
        when "Washroom"
          @parks = @parks.joins(:facilities).where("facilities.displayname like ?", "%Washroom%")
        when "Rink"
          @parks = @parks.joins(:facilities).where("facilities.displayname like ?", "%Rink%")
        when "Sports Area"
          @parks = @parks.joins(:facilities).where("facilities.displayname like ?", "%Sport Field%")
        when "Pool"
          @parks = @parks.joins(:facilities).where("facilities.displayname like ?", "%Pool%")
        when "Playground"
          @parks = @parks.joins(:facilities).where("facilities.displayname like ?", "%Playground%")
        when "Dog Playpark"
          @parks = @parks.joins(:facilities).where("facilities.displayname like ?", "%Dogs Off-Leash Area%")
        else
          puts "monkey's brain"
      end
    end
		render json: @parks
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/facilities/_form.html.erb
<%= form_for(@facility) do |f| %>
  <% if @facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
      <% @facility.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :displayname %><br>
    <%= f.text_field :displayname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facilities/edit.html.erb
<h1>Editing Facility</h1>

<%= render 'form' %>

<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Facilities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Displayname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facilities.each do |facility| %>
      <tr>
        <td><%= facility.name %></td>
        <td><%= facility.displayname %></td>
        <td><%= link_to 'Show', facility %></td>
        <td><%= link_to 'Edit', edit_facility_path(facility) %></td>
        <td><%= link_to 'Destroy', facility, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Facility', new_facility_path %>

app/views/facilities/new.html.erb
<h1>New Facility</h1>

<%= render 'form' %>

<%= link_to 'Back', facilities_path %>

app/views/facilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @facility.name %>
</p>

<p>
  <strong>Displayname:</strong>
  <%= @facility.displayname %>
</p>

<%= link_to 'Edit', edit_facility_path(@facility) %> |
<%= link_to 'Back', facilities_path %>

app/views/home/index.html.erb
<div id="form_fac">
 <%= form_tag parks_path, method: :get, id:"form_items" do %>





<!--   <div class="block-switch">
      <input id="toggle-flat" class="toggle toggle-flat" type="checkbox">
      <label for="toggle-flat"></label>
      <h4>Flat Switch</h4>
    </div> -->

    <div class="block-switch">
      <input id="toggle-flip" class="toggle toggle-flip" type="checkbox" value="Track">
      <label for="toggle-flip" data-on="Track" data-off="Track"></label>
      <!-- <h4>Flip Switch</h4> -->
   </div>

   <div class="block-switch">
      <input id="toggle-flip1" class="toggle toggle-flip" type="checkbox" value="Washroom">
      <label for="toggle-flip1" data-on="Washroom" data-off="Washroom"></label>
   </div>

	<div class="block-switch">
      <input id="toggle-flip2" class="toggle toggle-flip" type="checkbox" value="Sports Area">
      <label for="toggle-flip2" data-on="Sports" data-off="Sports"></label>
  </div>

	<div class="block-switch">
      <input id="toggle-flip3" class="toggle toggle-flip" type="checkbox" value="Pool">
      <label for="toggle-flip3" data-on="Pool" data-off="Pool"></label>
  </div>

  <div class="block-switch">
      <input id="toggle-flip4" class="toggle toggle-flip" type="checkbox" value="Dog Playpark">
      <label for="toggle-flip4" data-on="Dog" data-off="Dog"></label>
  </div>

  <div class="block-switch">
      <input id="toggle-flip5" class="toggle toggle-flip" type="checkbox" value="Playground">
      <label for="toggle-flip5" data-on="Playground" data-off="Playground"></label>
  </div>

  <div class="block-switch">
      <input id="toggle-flip6" class="toggle toggle-flip" type="checkbox" value="Rink">
      <label for="toggle-flip6" data-on="Rink" data-off="Rink"></label>
  </div>

<!-- 
 
  <div>
		<%= check_box_tag :track, "Washroom", false, id: "Washroom", class:'checkbox_filter' %>
    <%= label_tag "Washroom", nil, class: "label_filter" %> 
  </div>
  <div>
		<%= check_box_tag :track, "Sports Area", false, id: "Sports", class:'checkbox_filter' %>
    <%= label_tag "Sports" , nil, class: "label_filter" %> 
  </div>
  <div>
		<%= check_box_tag :track, "Pool", false, id: "Pool", class:'checkbox_filter' %>
    <%= label_tag "Pool", nil, class: "label_filter" %> 
  </div>
  <div>
		<%= check_box_tag :track, "Dog Playpark", false, id: "Dog", class:'checkbox_filter' %>
    <%= label_tag "Dog" , nil, class: "label_filter" %> 
  </div>
  <div> 
		<%= check_box_tag :track, "Playground", false, id: "Playground", class:'checkbox_filter' %>
    <%= label_tag "Playground", nil, class: "label_filter" %>
	</div>
	<div> 
		<%= check_box_tag :track, "Rink", false, id: "Rink", class:'checkbox_filter' %>
    <%= label_tag "Rink", nil, class: "label_filter" %>
	</div> -->
  <!-- <% end %> -->
</div>	

<nav id="navpos">
	<div>
		<div class="white-box" id="white-box"></div>
<!-- 		<div class="white-box1" id="white-box1"></div>
		<div class="white-box2" id="white-box2"></div>
		<div class="white-box3" id="white-box3"></div>
		<div class="white-box4" id="white-box4"></div> -->
	</div>
	Park Your Child 
</nav>

<!-- <nav class="navbar navbar-default">
 <div class="container-fluid">
   <div class="navbar-header">
     <a class="navbar-brand" href="#">
       <div class = "image">
       <img alt="Brand" src="/tree.jpg" id="brand"> 
         <span> Park Your Child</span>
       </div>
     </a>
   </div>
 </div>
</nav> -->


<div id="map"></div>
<div id="greenland"> 	</div>

<script>
  window.data = <%= @parks.to_json.html_safe %>;
  function initMap() {
    parkMap.initialize('map', data);
  }
  $(document).ready(function() {
    
  });
</script>

<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAOXLByKziSlHAOD4QCSxXgBuFbi_ImZfU&callback=initMap">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>
<title>Parkyourchild</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
	
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</head>

<body>
	<%= yield %>

</body>

<footer>
  <div id="footer" class="navbar navbar-fixed-bottom">
      <div class="container" >
           <div id="text-bottom">Park Your Child - A place to help families come together amongst urban nature</div>
         <div class="social">
            <img src="http://i.imgur.com/t62cuWR.png" class="social1">
            <img src="http://i.imgur.com/Xx6DQRZ.png" class="social2">
            <img src="http://i.imgur.com/7B9Z6kR.png" class="social3">
          </div>
      </div>
  </div>
</footer>

</html>

app/views/parks/_form.html.erb
<%= form_for(@park) do |f| %>
  <% if @park.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@park.errors.count, "error") %> prohibited this park from being saved:</h2>

      <ul>
      <% @park.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :postalcode %><br>
    <%= f.text_field :postalcode %>
  </div>
  <div class="field">
    <%= f.label :imgageurl %><br>
    <%= f.text_field :imgageurl %>
  </div>
  <div class="field">
    <%= f.label :cleanliness %><br>
    <%= f.number_field :cleanliness %>
  </div>
  <div class="field">
    <%= f.label :welllit %><br>
    <%= f.check_box :welllit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parks/edit.html.erb
<h1>Editing Park</h1>

<%= render 'form' %>

<%= link_to 'Show', @park %> |
<%= link_to 'Back', parks_path %>

app/views/parks/index.html.erb
  <%= form_tag(parks_path, :method => 'get') do %>
    <%= text_field_tag :search_displayname, params[:search], placeholder: "Search For Facilities" %>
     <%= submit_tag "Search" %>
  <% end %>

<p id="notice"><%= notice %></p>

<h1>Listing Parks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Postalcode</th>
      <th>Imgageurl</th>
      <th>Cleanliness</th>
      <th>Welllit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parks.each do |park| %>
      <tr>
        <td><%= park.name %></td>
        <td><%= park.address %></td>
        <td><%= park.postalcode %></td>
        <td><%= park.imgageurl %></td>
        <td><%= park.cleanliness %></td>
        <td><%= park.welllit %></td>
        <td><%= link_to 'Show', park %></td>
        <td><%= link_to 'Edit', edit_park_path(park) %></td>
        <td><%= link_to 'Destroy', park, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Park', new_park_path %>


 

app/views/parks/new.html.erb
<h1>New Park</h1>

<%= render 'form' %>

<%= link_to 'Back', parks_path %>

app/views/parks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @park.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @park.address %>
</p>

<p>
  <strong>Postalcode:</strong>
  <%= @park.postalcode %>
</p>

<p>
  <strong>Imgageurl:</strong>
  <%= @park.imgageurl %>
</p>

<p>
  <strong>Cleanliness:</strong>
  <%= @park.cleanliness %>
</p>

<p>
  <strong>Welllit:</strong>
  <%= @park.welllit %>
</p>

<%= link_to 'Edit', edit_park_path(@park) %> |
<%= link_to 'Back', parks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>